apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: custom-scheduler
  template:
    metadata:
      labels:
        component: custom-scheduler
    spec:
      containers:
      - name: custom-scheduler
        # Substitua <usuário-no-DockerHub>, <nome-da-imagem> e <tag> pelos valores corretos
        # Exemplo: usuarioTeste/custom-scheduler:latest
        # A imagem deve ser construída e enviada para o Docker Hub ou pode ser utilizada uma imagem que foi construida localmente,
        # mas nesse caso deve ser feito o envio da mesma para dentro do minikube, esse ultimo passo é realizado pelo bash build_and_load para facilidade.
        image: <usuário-no-DockerHub>/<nome-da-imagem>:<tag>
        command:
        - /custom-scheduler                
        args:
        - --config=/etc/kubernetes/scheduler-config.yaml
        - --pod-max-in-unschedulable-pods-duration=10s
        volumeMounts:
        - mountPath: /etc/kubernetes       
          name: config-volume
      volumes:
      - name: config-volume
        configMap:
          name: custom-scheduler-config