apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      serviceAccountName: custom-scheduler
      containers:
      - name: custom-scheduler
        image: brunogb123/custom-k8s-scheduler:0.1.10
        imagePullPolicy: Always
        command:
        - /usr/local/bin/custom-k8s-scheduler
        args:
        - --scheduler-name=my-custom-scheduler
