apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
- schedulerName: custom-scheduler
  plugins:
    queueSort:
      disabled:
      - name: QosAware
    reserve:
      enabled:
      - name: QosAware
    preBind:
      enabled:
      - name: QosAware
    postBind:
      enabled:
      - name: QosAware
    postFilter:
      enabled:
      - name: QosAware
