apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
- schedulerName: custom-scheduler
  plugins:
    queueSort:
      enabled:
      - name: QosAware
      disabled:
      - name: "*"
    reserve:
      enabled:
      - name: QosAware
    preBind:
      enabled:
      - name: QosAware
    postBind:
      enabled:
      - name: QosAware
    postFilter:
      enabled:
      - name: QosAware
  pluginConfig:
    - name: QosAware
      args:
        safetyMargin: 30s
        minimumRunningTime: 30s

