apiVersion: v1
kind: Pod
metadata:
  name: pod-bloqueador-cpu
  namespace: kube-system
spec:
  priorityClassName: gold-priority
  containers:
    - name: bloqueador
      image: nginx
      resources:
        requests:
          cpu: "110m"
        limits:
          cpu: "110m"
