apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment2
  labels:
    app: test-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app2
  template:
    metadata:
      labels:
        app: test-app2
      annotations:
        controller: "test-controller2"  # Annotation necessária para controllerName
    spec:
      priorityClassName: batch-priority
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1000m"
          limits:
            cpu: "1000m"
      schedulerName: custom-scheduler
