apiVersion: v1
kind: Pod
metadata:
  name: high-priority-pod
  labels:
    app: test-app
  annotations:
    controller: "test-controller"  # Annotation necessária para controllerName
spec:
  priorityClassName: prod-priority
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "8000m"
        memory: "268Mi"
      limits:
        cpu: "8000m"
        memory: "268Mi"
  schedulerName: custom-scheduler
