apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
  annotations:
    controller: "test-controller2"  # Annotation necessária para controllerName
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1000m"
      limits:
        cpu: "1000m"
  schedulerName: custom-scheduler
